scrape_configs:
  - job_name: 'pushgateway'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['prom-pushgateway:9091']
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:8080']
